import { useNavigate } from 'react-router-dom'
import { ChevronLeft } from 'lucide-react'

const GOLD = '#C6A85C'
const TEXT = '#F0EDE8'
const TEXT_DIM = '#5A5652'
const BORDER = 'rgba(255,255,255,0.07)'

function Section({ title, children }) {
  return (
    <div className="mb-6">
      <h2 className="font-heading font-bold text-[15px] mb-2" style={{ color: GOLD }}>{title}</h2>
      <div className="font-body text-[13px] leading-relaxed space-y-2" style={{ color: TEXT_DIM }}>
        {children}
      </div>
    </div>
  )
}

export default function Terms() {
  const navigate = useNavigate()

  return (
    <div className="page-scroll-full" style={{ background: '#080808' }}>
      {/* Header */}
      <div className="flex items-center gap-3 px-4 pt-14 pb-4" style={{ borderBottom: `1px solid ${BORDER}` }}>
        <button
          onClick={() => navigate(-1)}
          className="w-9 h-9 rounded-xl flex items-center justify-center"
          style={{ background: 'rgba(255,255,255,0.05)' }}
        >
          <ChevronLeft size={18} style={{ color: TEXT }} />
        </button>
        <div>
          <h1 className="font-heading font-bold text-[17px]" style={{ color: TEXT }}>Terms of Service</h1>
          <p className="text-[11px] font-body" style={{ color: TEXT_DIM }}>Last updated: April 2025</p>
        </div>
      </div>

      <div className="px-5 py-6 pb-20 max-w-2xl mx-auto">
        <div className="mb-6 px-4 py-4 rounded-2xl" style={{ background: 'rgba(198,168,92,0.06)', border: '1px solid rgba(198,168,92,0.2)' }}>
          <p className="font-body text-[12px] leading-relaxed" style={{ color: 'rgba(198,168,92,0.8)' }}>
            These Terms of Service govern your use of Ascendus, operated by Ascendus Inc. (Ontario, Canada). By using Ascendus you agree to these terms. If you do not agree, do not use the app.
          </p>
        </div>

        <Section title="1. Eligibility">
          <p><strong style={{ color: TEXT }}>You must be 17 years of age or older to use Ascendus.</strong> By creating an account, you confirm that you meet this age requirement. We reserve the right to terminate accounts of users found to be under 17.</p>
        </Section>

        <Section title="2. Description of Service">
          <p>Ascendus is a self-improvement application that uses AI to analyze facial and body photos to provide appearance scores, personalized improvement plans, and progress tracking. Ascendus is for personal, non-commercial use only.</p>
        </Section>

        <Section title="3. AI Scores — Not Medical Advice">
          <p><strong style={{ color: TEXT }}>All scores, analyses, and recommendations generated by Ascendus are produced by artificial intelligence and are estimates only.</strong> They are not medical, clinical, or professional assessments. Ascendus does not claim to provide any form of medical diagnosis or advice.</p>
          <p className="mt-2">Do not make medical, health, or surgical decisions based on Ascendus scores. Always consult a qualified healthcare professional for medical advice.</p>
          <p className="mt-2">Ascendus AI is not a medical professional. We never use language such as "clinically accurate" or imply that our scores carry clinical weight.</p>
        </Section>

        <Section title="4. Your Photos & Data">
          <p><strong style={{ color: TEXT }}>You own your photos.</strong> By uploading photos to Ascendus, you grant us a limited license to process them solely for the purpose of providing the service.</p>
          <p className="mt-2">We do not claim ownership of your photos, sell them to third parties, or use them to train AI models. See our Privacy Policy for full details on how photos are processed.</p>
          <p className="mt-2">You are responsible for ensuring you have the right to upload any photo you submit. Do not upload photos of other people without their explicit consent.</p>
        </Section>

        <Section title="5. Prohibited Conduct">
          <p>You agree not to:</p>
          <ul className="list-disc pl-4 space-y-1 mt-1">
            <li>Use Ascendus if you are under 17 years of age</li>
            <li>Upload photos of other people without their consent</li>
            <li>Use the service for any unlawful purpose</li>
            <li>Attempt to reverse-engineer, scrape, or abuse the API</li>
            <li>Share your account credentials with others</li>
            <li>Use Ascendus to harass, demean, or rate others without their knowledge</li>
          </ul>
          <p className="mt-2">We reserve the right to suspend or permanently delete accounts that violate these terms without refund.</p>
        </Section>

        <Section title="6. Celebrity Comparisons">
          <p>Celebrity lookalike comparisons are AI-generated estimates based on facial feature analysis. They do not imply any connection to, endorsement by, or relationship with the named individuals. All celebrity names are used for reference purposes only.</p>
        </Section>

        <Section title="7. Subscriptions & Payments">
          <p><strong style={{ color: TEXT }}>Billing:</strong> Ascendus Premium is billed at $9.99/month or $59.99/year (prices shown at checkout). You will be clearly informed of the exact charge before confirming your subscription.</p>
          <p className="mt-2"><strong style={{ color: TEXT }}>Free trial:</strong> If a free trial is offered, you will not be charged until the trial period ends. You may cancel at any time before the trial ends to avoid charges.</p>
          <p className="mt-2"><strong style={{ color: TEXT }}>Cancellation:</strong> You may cancel your subscription at any time through the Subscription settings in your Profile. Cancellation takes effect at the end of the current billing period. No partial refunds are issued for unused time.</p>
          <p className="mt-2"><strong style={{ color: TEXT }}>Refunds:</strong> Refund requests must be submitted within 7 days of charge to support@ascendus.com. We review refund requests on a case-by-case basis. Subscription fees are generally non-refundable after the 7-day window.</p>
          <p className="mt-2">All payments are processed by Stripe. We do not store your payment card details.</p>
        </Section>

        <Section title="8. Intellectual Property">
          <p>Ascendus, its logo, design, code, and content are the intellectual property of Ascendus Inc. You may not reproduce, distribute, or create derivative works without our written permission.</p>
        </Section>

        <Section title="9. Disclaimer of Warranties">
          <p>Ascendus is provided "as is" without warranties of any kind, express or implied. We do not guarantee that:</p>
          <ul className="list-disc pl-4 space-y-1 mt-1">
            <li>The service will be uninterrupted or error-free</li>
            <li>AI scores are accurate or complete</li>
            <li>Following recommendations will produce specific results</li>
          </ul>
        </Section>

        <Section title="10. Limitation of Liability">
          <p>To the maximum extent permitted by applicable law, Ascendus Inc. shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service. Our total liability to you shall not exceed the amount you paid to us in the 12 months preceding the claim.</p>
        </Section>

        <Section title="11. Mental Health">
          <p>Ascendus is designed as a self-improvement tool, not a validation platform. If you experience distress related to appearance, body image, or self-esteem while using Ascendus, we encourage you to stop using the app and speak with a qualified mental health professional.</p>
          <p className="mt-2">Canada crisis line: 1-866-APPELLE (277-3553) · Crisis Text Line: Text HOME to 741741</p>
        </Section>

        <Section title="12. Governing Law">
          <p>These Terms are governed by the laws of the Province of Ontario and the federal laws of Canada applicable therein. Any disputes shall be resolved in the courts of Ontario, Canada.</p>
        </Section>

        <Section title="13. Changes to These Terms">
          <p>We may update these Terms from time to time. We will notify you of material changes via email or in-app notification. Continued use of Ascendus after changes constitutes acceptance of the updated Terms.</p>
        </Section>

        <Section title="14. Contact">
          <p><strong style={{ color: TEXT }}>Support:</strong> support@ascendus.com</p>
          <p><strong style={{ color: TEXT }}>Company:</strong> Ascendus Inc., Ontario, Canada</p>
        </Section>

        <p className="text-center font-body text-[11px] mt-6" style={{ color: TEXT_DIM }}>
          Ascendus v1.0 · © 2025 Ascendus Inc. · Ontario, Canada
        </p>
      </div>
    </div>
  )
}
